laravel/app/routes.php
<?php

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::post('cadastroNewsletter', 'HomeController@cadastro');
Route::post('envioContato', 'HomeController@contato');
Route::get('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('o-pieron/{slug_texto?}', array('as' => 'opieron', 'uses' => 'OPieronController@index'));
Route::get('atuacao/{slug_texto?}', array('as' => 'atuacao', 'uses' => 'AtuacaoController@index'));
Route::get('flow-conditions-system', array('as' => 'flowconditions', 'uses' => 'FlowConditionsController@index'));
Route::get('venda-de-materiais', array('as' => 'materiais', 'uses' => 'MateriaisController@index'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::get('cursos-e-treinamentos', array('as' => 'cursos', 'uses' => 'CursosController@index'));
Route::get('cursos-e-treinamentos/area/{slug_area?}', array('as' => 'cursos.areas', 'uses' => 'CursosController@index'));
Route::get('cursos-e-treinamentos/detalhes/{slug_curso?}', array('as' => 'cursos.detalhes', 'uses' => 'CursosController@detalhes'));
Route::get('publicacoes', array('as' => 'publicacoes', 'uses' => 'PublicacoesController@artigos'));
Route::get('publicacoes/clipping', array('as' => 'publicacoes.clipping', 'uses' => 'PublicacoesController@clipping'));
Route::get('publicacoes/clipping/{slug?}', array('as' => 'publicacoes.clipping.detalhes', 'uses' => 'PublicacoesController@galeria'));
Route::get('publicacoes/artigos', array('as' => 'publicacoes.artigos', 'uses' => 'PublicacoesController@artigos'));
Route::get('publicacoes/artigos/{slug?}', array('as' => 'publicacoes.artigos.detalhes', 'uses' => 'PublicacoesController@artigosDetalhes'));
Route::get('publicacoes/download/{slug?}', array('as' => 'publicacoes.artigos.download', 'uses' => 'PublicacoesController@download'));

Route::get('lang/{sigla_idioma?}', function($sigla_idioma){
	if($sigla_idioma == 'pt' || $sigla_idioma == 'en'){
		Session::put('locale', $sigla_idioma);
		App::setLocale($sigla_idioma);
	}

	return Redirect::back();	
});

Route::get('cursos/ordenarData', function(){
	Session::put('ordenacaoCursos', 'data_inicio');
	return Redirect::back();
});

Route::get('cursos/ordenarNome', function(){
	Session::put('ordenacaoCursos', 'alfabetica');
	return Redirect::back();
});

// Route::any('painel{all}', function(){
// 	return View::make('backend.templates.manutencao');
// })->where('all', '.*');

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

//Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::has('lembrar') && Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));


Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{

    Route::get('download', function(){

    	$filename = 'cadastros_'.date('d-m-Y-H-i-s');

		Excel::create($filename, function($excel) {
		    $excel->sheet('Usuários Cadastrados', function($sheet) {
		        $sheet->fromModel(\Cadastro::select('nome', 'email')->orderBy('nome')->get());
		    });
		})->download('csv');
    });

    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('banners', 'Painel\BannersController');
	Route::resource('chamadas', 'Painel\ChamadasController');
	Route::resource('cadastros', 'Painel\CadastrosController');
	Route::resource('opieron', 'Painel\OPieronController');
	Route::resource('equipe', 'Painel\EquipeController');
	Route::resource('unidades', 'Painel\UnidadesController');
	Route::resource('cursosareas', 'Painel\CursosAreasController');
	Route::resource('cursos', 'Painel\CursosController');
	Route::resource('turmas', 'Painel\TurmasController');
	Route::resource('materiais', 'Painel\MateriaisController');
	Route::resource('flowconditionssystem', 'Painel\FlowConditionsSystemController');
	Route::resource('atuacao', 'Painel\AtuacaoController');
	Route::resource('areasatuacao', 'Painel\AreasAtuacaoController');
	Route::resource('imagenstopo', 'Painel\ImagensTopoController');
	Route::resource('historia', 'Painel\HistoriaController');
	Route::resource('clippings', 'Painel\ClippingsController');
	Route::resource('artigos', 'Painel\ArtigosController');
	Route::resource('clippingimagens', 'Painel\ClippingImagensController');
	Route::resource('contatos', 'Painel\ContatosController');
//NOVASROTASDOPAINEL//
});

laravel/app/models/Artigo.php
<?php

class Artigo extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'artigos';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

    public function scopeOrdenado($query){
    	return $query->orderBy('data', 'DESC');
    }
}

laravel/app/controllers/painel/ArtigosController.php
<?php

namespace Painel;

use \View, \Input, \Str, \Session, \Redirect, \Hash, \Thumb, \Tools, \File, \Artigo;

class ArtigosController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = false;

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('backend.artigos.index')->with('registros', Artigo::ordenado()->paginate(25));		
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.artigos.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new Artigo;

		$object->titulo = Input::get('titulo');
		$object->titulo_us = Input::get('titulo_us');
		$object->autor = Input::get('autor');
		$object->data = Tools::converteData(Input::get('data'));
		$object->olho = Input::get('olho');
		$object->olho_us = Input::get('olho_us');
		$object->texto = Input::get('texto');
		$object->texto_us = Input::get('texto_us');

		if(Input::hasFile('pdf')){
			$arquivo = Input::file('pdf');
			$arquivo->move('assets/files/artigos', $arquivo->getClientOriginalName());
			$object->pdf = $arquivo->getClientOriginalName();
		}

		if(Input::has('remover_arquivo') && Input::get('remover_arquivo') == 1)
			$object->pdf = null;
		
		try {

			$object->save();

			$object->slug = \Str::slug(\Tools::slugData(Input::get('data')).' '.Input::get('titulo').' '.$object->id);
			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Artigo criado com sucesso.');
			return Redirect::route('painel.artigos.index');

		} catch (\Exception $e) {

			return Redirect::back()->withErrors($e->getMessage());

		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.artigos.edit')->with('registro', Artigo::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Artigo::find($id);

		$object->titulo = Input::get('titulo');
		$object->titulo_us = Input::get('titulo_us');
		$object->autor = Input::get('autor');
		$object->data = Tools::converteData(Input::get('data'));
		$object->olho = Input::get('olho');
		$object->olho_us = Input::get('olho_us');
		$object->texto = Input::get('texto');
		$object->texto_us = Input::get('texto_us');
		$object->slug = \Str::slug(\Tools::slugData(Input::get('data')).' '.Input::get('titulo').' '.$object->id);			

		if(Input::hasFile('pdf')){
			$arquivo = Input::file('pdf');
			$arquivo->move('assets/files/artigos', $arquivo->getClientOriginalName());
			$object->pdf = $arquivo->getClientOriginalName();
		}

		if(Input::has('remover_arquivo') && Input::get('remover_arquivo') == 1)
			$object->pdf = null;
		

		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Artigo alterado com sucesso.');
			return Redirect::route('painel.artigos.index');

		} catch (\Exception $e) {

			return Redirect::back()->withErrors($e->getMessage());

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = Artigo::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Artigo removido com sucesso.');

		return Redirect::route('painel.artigos.index');
	}

}

laravel/app/views/backend/artigos/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Artigo
        </h2>  

		{{ Form::open( array('route' => array('painel.artigos.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	


				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" value="{{$registro->titulo}}" required>
				</div>
				
				<div class="form-group">
					<label for="inputTítulo em inglês">Título em inglês</label>
					<input type="text" class="form-control" id="inputTítulo em inglês" name="titulo_us" value="{{$registro->titulo_us}}" >
				</div>
				
				<div class="form-group">
					<label for="inputAutor">Autor</label>
					<input type="text" class="form-control" id="inputAutor" name="autor" value="{{$registro->autor}}" required>
				</div>
				
				<div class="form-group">
					<label for="inputData de Publicação">Data de Publicação</label>
					<input type="text" class="form-control datepicker" id="inputData de Publicação" name="data" value="{{ Tools::converteData($registro->data) }}" required>
				</div>
				
				<div class="form-group">
					<label for="inputOlho">Olho</label>
					<textarea name="olho" class="form-control" id="inputOlho" >{{$registro->olho }}</textarea>
				</div>
				
				<div class="form-group">
					<label for="inputOlho em inglês">Olho em inglês</label>
					<textarea name="olho_us" class="form-control" id="inputOlho em inglês" >{{$registro->olho_us }}</textarea>
				</div>
				
				<div class="form-group">
					<label for="inputTexto">Texto</label>
					<textarea name="texto" class="form-control" id="inputTexto" >{{$registro->texto }}</textarea>
				</div>
				
				<div class="form-group">
					<label for="inputTexto em inglês">Texto em inglês</label>
					<textarea name="texto_us" class="form-control" id="inputTexto em inglês" >{{$registro->texto_us }}</textarea>
				</div>

				<div class="form-group">
					@if($registro->pdf)
						<div class="well">	
							Arquivo Atual: <a href="assets/files/artigos/{{$registro->pdf}}" title="Ver arquivo" target="_blank">{{$registro->pdf}}</a><br>
							<label for="inputImagem">Trocar Arquivo PDF</label>
							<input type="file" class="form-control" id="inputImagem" name="pdf"><br><br>
							<label><input type="checkbox" name="remover_arquivo" value="1"> Não disponibilizar nenhum arquivo</label>
						</div>
					@else
						<label for="inputArquivo">Arquivo PDF</label>
						<input type="file" class="form-control" id="inputArquivo" name="pdf">
					@endif
				</div>
				
				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.artigos.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/artigos/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Artigo
        </h2>  

		<form action="{{URL::route('painel.artigos.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif


				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['titulo'] }}" @endif required>
				</div>
				
				<div class="form-group">
					<label for="inputTítulo em inglês">Título em inglês</label>
					<input type="text" class="form-control" id="inputTítulo em inglês" name="titulo_us" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['titulo_us'] }}" @endif >
				</div>
				
				<div class="form-group">
					<label for="inputAutor">Autor</label>
					<input type="text" class="form-control" id="inputAutor" name="autor" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['autor'] }}" @endif required>
				</div>
				
				<div class="form-group">
					<label for="inputData de Publicação">Data de Publicação</label>
					<input type="text" class="form-control datepicker" id="inputData de Publicação" name="data" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['data'] }}" @endif required>
				</div>
				
				<div class="form-group">
					<label for="inputOlho">Olho</label>
					<textarea name="olho" class="form-control" id="inputOlho" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['olho'] }} @endif</textarea>
				</div>
				
				<div class="form-group">
					<label for="inputOlho em inglês">Olho em inglês</label>
					<textarea name="olho_us" class="form-control" id="inputOlho em inglês" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['olho_us'] }} @endif</textarea>
				</div>
				
				<div class="form-group">
					<label for="inputTexto">Texto</label>
					<textarea name="texto" class="form-control" id="inputTexto" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['texto'] }} @endif</textarea>
				</div>
				
				<div class="form-group">
					<label for="inputTexto em inglês">Texto em inglês</label>
					<textarea name="texto_us" class="form-control" id="inputTexto em inglês" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['texto_us'] }} @endif</textarea>
				</div>

				<div class="form-group">
					<label for="inputArquivo">Arquivo PDF</label>
					<input type="file" class="form-control" id="inputArquivo" name="pdf">
				</div>
				

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.artigos.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/artigos/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Artigos <a href='{{ URL::route('painel.artigos.create') }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Artigo</a>
    </h2>

    <table class='table table-striped table-bordered table-hover'>

        <thead>
            <tr>
                <th>Título</th>
				<th>Autor</th>
				<th>Data de Publicação</th>
				<th>Olho</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
                <td>{{ $registro->titulo }}</td>
				<td>{{ $registro->autor }}</td>
				<td>{{ Tools::converteData($registro->data) }}</td>
				<td>{{ Str::words(strip_tags($registro->olho), 15) }}</td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.artigos.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>
						{{ Form::open(array('route' => array('painel.artigos.destroy', $registro->id), 'method' => 'delete')) }}
							<button type='submit' class='btn btn-danger btn-sm btn-delete'>excluir</button>
						{{ Form::close() }}                    
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    {{ $registros->links() }}
</div>

@stop