laravel/app/routes.php
<?php

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::post('cadastroNewsletter', 'HomeController@cadastro');
Route::post('envioContato', 'HomeController@contato');
Route::get('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('o-pieron/{slug_texto?}', array('as' => 'opieron', 'uses' => 'OPieronController@index'));
Route::get('atuacao/{slug_texto?}', array('as' => 'atuacao', 'uses' => 'AtuacaoController@index'));
Route::get('flow-conditions-system', array('as' => 'flowconditions', 'uses' => 'FlowConditionsController@index'));
Route::get('venda-de-materiais', array('as' => 'materiais', 'uses' => 'MateriaisController@index'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::get('cursos-e-treinamentos', array('as' => 'cursos', 'uses' => 'CursosController@index'));
Route::get('cursos-e-treinamentos/area/{slug_area?}', array('as' => 'cursos.areas', 'uses' => 'CursosController@index'));
Route::get('cursos-e-treinamentos/detalhes/{slug_curso?}', array('as' => 'cursos.detalhes', 'uses' => 'CursosController@detalhes'));
Route::get('publicacoes', array('as' => 'publicacoes', 'uses' => 'PublicacoesController@artigos'));
Route::get('publicacoes/clipping', array('as' => 'publicacoes.clipping', 'uses' => 'PublicacoesController@clipping'));
Route::get('publicacoes/clipping/{slug?}', array('as' => 'publicacoes.clipping.detalhes', 'uses' => 'PublicacoesController@galeria'));
Route::get('publicacoes/artigos', array('as' => 'publicacoes.artigos', 'uses' => 'PublicacoesController@artigos'));
Route::get('publicacoes/artigos/{slug?}', array('as' => 'publicacoes.artigos.detalhes', 'uses' => 'PublicacoesController@artigosDetalhes'));
Route::get('publicacoes/download/{slug?}', array('as' => 'publicacoes.artigos.download', 'uses' => 'PublicacoesController@download'));

Route::get('lang/{sigla_idioma?}', function($sigla_idioma){
	if($sigla_idioma == 'pt' || $sigla_idioma == 'en'){
		Session::put('locale', $sigla_idioma);
		App::setLocale($sigla_idioma);
	}

	return Redirect::back();	
});

Route::get('cursos/ordenarData', function(){
	Session::put('ordenacaoCursos', 'data_inicio');
	return Redirect::back();
});

Route::get('cursos/ordenarNome', function(){
	Session::put('ordenacaoCursos', 'alfabetica');
	return Redirect::back();
});

// Route::any('painel{all}', function(){
// 	return View::make('backend.templates.manutencao');
// })->where('all', '.*');

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

//Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::has('lembrar') && Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));


Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{

    Route::get('download', function(){

    	$filename = 'cadastros_'.date('d-m-Y-H-i-s');

		Excel::create($filename, function($excel) {
		    $excel->sheet('Usuários Cadastrados', function($sheet) {
		        $sheet->fromModel(\Cadastro::select('nome', 'email')->orderBy('nome')->get());
		    });
		})->download('csv');
    });

    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('banners', 'Painel\BannersController');
	Route::resource('chamadas', 'Painel\ChamadasController');
	Route::resource('cadastros', 'Painel\CadastrosController');
	Route::resource('opieron', 'Painel\OPieronController');
	Route::resource('equipe', 'Painel\EquipeController');
	Route::resource('unidades', 'Painel\UnidadesController');
	Route::resource('cursosareas', 'Painel\CursosAreasController');
	Route::resource('cursos', 'Painel\CursosController');
	Route::resource('turmas', 'Painel\TurmasController');
	Route::resource('materiais', 'Painel\MateriaisController');
	Route::resource('flowconditionssystem', 'Painel\FlowConditionsSystemController');
	Route::resource('atuacao', 'Painel\AtuacaoController');
	Route::resource('areasatuacao', 'Painel\AreasAtuacaoController');
	Route::resource('imagenstopo', 'Painel\ImagensTopoController');
	Route::resource('historia', 'Painel\HistoriaController');
	Route::resource('clippings', 'Painel\ClippingsController');
	Route::resource('artigos', 'Painel\ArtigosController');
	Route::resource('clippingimagens', 'Painel\ClippingImagensController');
	Route::resource('contatos', 'Painel\ContatosController');
//NOVASROTASDOPAINEL//
});

laravel/app/models/OPieron.php
<?php

class OPieron extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'empresa_textos';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

    public function scopeOrdenado($query)
    {
    	return $query->orderBy('ordem', 'asc')->get();
    }

}

laravel/app/controllers/OPieronController.php
<?php

use \OPieron, \ImagensTopo, \Equipe, \Historia;

class OPieronController extends BaseController {

	protected $layout = 'frontend.templates.index';

	public function index($slug_texto = false)
	{

		if(!$slug_texto)
			$detalhe = OPieron::orderBy('ordem', 'asc')->first();
		else{
			$detalhe = OPieron::where('slug', '=', $slug_texto)->first();

			if(is_null($detalhe)){
				App::abort('404');
			}
		}

		$this->layout->with('marcarSub', $detalhe->{Lang::get('base.campos.slug')});
		$this->layout->content = View::make('frontend.opieron.index')->with('textos', OPieron::ordenado())
																	 ->with('detalhe', $detalhe)
																	 ->with('slugFiltro', $detalhe->{Lang::get('base.campos.slug')})
																	 ->with('listaHistoria', Historia::ordenado())
																	 ->with('listaEquipe', Equipe::ordenado())
																	 ->nest('formulario', 'frontend.partials.formulario')
																	 ->nest('topo', 'frontend.partials.topo', array(
																	 		'bannerTopo' => ImagensTopo::where('slug', '=', 'opieron')->first(),
																	 		'textoArea' => Lang::get('base.secoes.opieron')
																	 ));
	}

}

laravel/app/controllers/painel/OPieronController.php
<?php

namespace Painel;

use \View, \Input, \Str, \Session, \Redirect, \Hash, \Thumb, \Tools, \File, OPieron;

class OPieronController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = false;

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('backend.opieron.index')->with('registros', OPieron::orderBy('ordem', 'ASC')->get());		
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.opieron.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new OPieron;

		$object->titulo = Input::get('titulo');
		$object->titulo_us = Input::get('titulo_us');
		$object->texto = Input::get('texto');
		$object->texto_us = Input::get('texto_us');
		$object->slug = Str::slug(Input::get('titulo'));

		if(sizeof(OPieron::where('slug', '=', $object->slug)->get()))
			return Redirect::back()->withErrors(array('Este título já está sendo utilizado!'));

		try {

			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Texto criado com sucesso.');
			return Redirect::route('painel.opieron.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Texto!'));	

		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.opieron.edit')->with('registro', OPieron::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = OPieron::find($id);

		$object->titulo = Input::get('titulo');
		$object->titulo_us = Input::get('titulo_us');
		$object->texto = Input::get('texto');
		$object->texto_us = Input::get('texto_us');
		if($object->slug != 'proposito' && $object->slug != 'como-trabalhamos' && $object->slug != 'historia' && $object->slug != 'equipe' && $object->slug != 'internacional'){
			$object->slug = Str::slug(Input::get('titulo'));
		}

		if(sizeof(OPieron::where('slug', '=', $object->slug)->where('id', '!=', $object->id)->get()))
			return Redirect::back()->withErrors(array('Este título já está sendo utilizado!'));

		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Texto alterado com sucesso.');
			return Redirect::route('painel.opieron.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Texto!'));

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = OPieron::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Texto removido com sucesso.');

		return Redirect::route('painel.opieron.index');
	}

}

laravel/app/views/backend/opieron/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Texto
        </h2>  

		{{ Form::open( array('route' => array('painel.opieron.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif

				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" value="{{$registro->titulo}}" required>					
				</div>

				<div class="form-group">
					<label for="inputTítuloUS">Título em inglês</label>
					<input type="text" class="form-control" id="inputTítuloUS" name="titulo_us" value="{{$registro->titulo_us}}" required>					
				</div>
				
				<div class="form-group large">
					<label for="inputTexto">Texto</label>
					<textarea name="texto" class="form-control" id="inputTexto" >{{$registro->texto }}</textarea>
				</div>

				<div class="form-group large">
					<label for="inputTextoUS">Texto em inglês</label>
					<textarea name="texto_us" class="form-control" id="inputTextoUS" >{{$registro->texto_us }}</textarea>
				</div>
				

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.opieron.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/opieron/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Texto
        </h2>  

		<form action="{{URL::route('painel.opieron.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif


				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['titulo'] }}" @endif required>
				</div>

				<div class="form-group">
					<label for="inputTítuloUS">Título em inglês</label>
					<input type="text" class="form-control" id="inputTítuloUS" name="titulo_us" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['titulo_us'] }}" @endif required>
				</div>
				
				<div class="form-group large">
					<label for="inputTexto">Texto</label>
					<textarea name="texto" class="form-control" id="inputTexto" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['texto'] }} @endif</textarea>
				</div>

				<div class="form-group large">
					<label for="inputTextoUS">Texto em inglês</label>
					<textarea name="texto_us" class="form-control" id="inputTextoUS" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['texto_us'] }} @endif</textarea>
				</div>
				

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.opieron.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/opieron/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        O Pieron <a href='{{ URL::route('painel.opieron.create') }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Texto</a>
    </h2>

    <table class='table table-striped table-bordered table-hover table-sortable' data-tabela='empresa_textos'>

        <thead>
            <tr>
                <th>Ordenar</th>
				<th>Título</th>
				<th>Texto</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
                <td class='move-actions'><a href='#' class='btn btn-info btn-move btn-sm'>mover</a></td>
				<td>{{ $registro->titulo }}</td>
				<td>{{ Str::words(strip_tags($registro->texto), 15) }}</td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.opieron.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>
                    @if($registro->slug != 'proposito' && $registro->slug != 'como-trabalhamos' && $registro->slug != 'historia' && $registro->slug != 'equipe' && $registro->slug != 'internacional')
					{{ Form::open(array('route' => array('painel.opieron.destroy', $registro->id), 'method' => 'delete')) }}
						<button type='submit' class='btn btn-danger btn-sm btn-delete'>excluir</button>
					{{ Form::close() }}
                    @endif
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    
</div>

@stop